export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE";

export const GET_BY_CATEGORY_BEAUTY_REQUEST = "GET_BY_CATEGORY_BEAUTY_REQUEST";
export const GET_BY_CATEGORY_BEAUTY_SUCCESS = "GET_BY_CATEGORY_BEAUTY_SUCCESS";
export const GET_BY_CATEGORY_BEAUTY_FAILURE = "GET_BY_CATEGORY_BEAUTY_FAILURE";

export const GET_BY_CATEGORY_BAKERY_REQUEST = "GET_BY_CATEGORY_BAKERY_REQUEST";
export const GET_BY_CATEGORY_BAKERY_SUCCESS = "GET_BY_CATEGORY_BAKERY_SUCCESS";
export const GET_BY_CATEGORY_BAKERY_FAILURE = "GET_BY_CATEGORY_BAKERY_FAILURE";

export const GET_BY_CATEGORY_VEGETABLES_REQUEST = "GET_BY_CATEGORY_VEGETABLES_REQUEST";
export const GET_BY_CATEGORY_VEGETABLES_SUCCESS = "GET_BY_CATEGORY_VEGETABLES_SUCCESS";
export const GET_BY_CATEGORY_VEGETABLES_FAILURE = "GET_BY_CATEGORY_VEGETABLES_FAILURE";

export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE";

export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAILURE = "GET_SINGLE_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";
