
export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE";


export const GET_BY_CATEGORY_BEAUTY_REQUEST = "GET_BY_CATEGORY_BEAUTY_REQUEST";
export const GET_BY_CATEGORY_BEAUTY_SUCCESS = "GET_BY_CATEGORY_BEAUTY_SUCCESS";
export const GET_BY_CATEGORY_BEAUTY_FAILURE = "GET_BY_CATEGORY_BEAUTY_FAILURE";
// 